CREATE TABLE IF NOT EXISTS users (
  google_id TEXT PRIMARY KEY,
  email TEXT UNIQUE,
  gamertag TEXT NOT NULL UNIQUE,
  avatar_url TEXT,
  phone TEXT,
  role TEXT DEFAULT 'PLAYER' CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'PLAYER')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS competitions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('LIGA', 'TORNEO')),
  status TEXT DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ACTIVE', 'FINISHED')),
  admin_id TEXT,
  invite_code TEXT UNIQUE,
  parent_league_id INTEGER,
  counts_for_league INTEGER DEFAULT 0 CHECK (counts_for_league IN (0, 1)),
  rules TEXT,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES users(google_id),
  FOREIGN KEY (parent_league_id) REFERENCES competitions(id)
);

CREATE TABLE IF NOT EXISTS squads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competition_id INTEGER,
  name TEXT NOT NULL,
  leader_id TEXT NOT NULL,
  max_members INTEGER DEFAULT 4,
  FOREIGN KEY (competition_id) REFERENCES competitions(id),
  FOREIGN KEY (leader_id) REFERENCES users(google_id)
);

CREATE TABLE IF NOT EXISTS squad_members (
  squad_id INTEGER,
  user_id TEXT,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACTIVE', 'LEFT', 'REJECTED')),
  PRIMARY KEY (squad_id, user_id),
  FOREIGN KEY (squad_id) REFERENCES squads(id),
  FOREIGN KEY (user_id) REFERENCES users(google_id)
);

CREATE TABLE IF NOT EXISTS matches (
  match_id TEXT PRIMARY KEY,
  competition_id INTEGER,
  submitted_by TEXT,
  mode TEXT,
  position TEXT,
  total_score INTEGER DEFAULT 0,
  total_eliminations INTEGER DEFAULT 0,
  total_kills INTEGER DEFAULT 0,
  total_assists INTEGER DEFAULT 0,
  total_redeploys INTEGER DEFAULT 0,
  total_damage INTEGER DEFAULT 0,
  audit_status TEXT DEFAULT 'APPROVED' CHECK (audit_status IN ('APPROVED', 'PENDING', 'REJECTED')),
  audit_notes TEXT,
  processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (competition_id) REFERENCES competitions(id),
  FOREIGN KEY (submitted_by) REFERENCES users(google_id)
);

CREATE TABLE IF NOT EXISTS stats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id TEXT,
  user_id TEXT,
  score INTEGER DEFAULT 0,
  eliminations INTEGER DEFAULT 0,
  kills INTEGER DEFAULT 0,
  assists INTEGER DEFAULT 0,
  redeploys INTEGER DEFAULT 0,
  damage INTEGER DEFAULT 0,
  placement_points INTEGER DEFAULT 0,
  UNIQUE (match_id, user_id),
  FOREIGN KEY (match_id) REFERENCES matches(match_id),
  FOREIGN KEY (user_id) REFERENCES users(google_id)
);

CREATE TABLE IF NOT EXISTS tournament_organizers (
  competition_id INTEGER,
  user_id TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (competition_id, user_id),
  FOREIGN KEY (competition_id) REFERENCES competitions(id),
  FOREIGN KEY (user_id) REFERENCES users(google_id)
);

CREATE TABLE IF NOT EXISTS competition_members (
  competition_id INTEGER,
  user_id TEXT,
  role TEXT DEFAULT 'PLAYER' CHECK (role IN ('ADMIN', 'ORGANIZER', 'PLAYER')),
  status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'LEFT', 'BANNED')),
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (competition_id, user_id),
  FOREIGN KEY (competition_id) REFERENCES competitions(id),
  FOREIGN KEY (user_id) REFERENCES users(google_id)
);

